POST http://localhost:3001/api/userds/
Content-Type: application/json

{
    "username": "admin2",
    "name": "adminname",
    "password": "adminpw"
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "adminpw"
}
###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlkIjoiNjEzNTY5Y2Y1ZGUwMThiNzY3ZGViYmRjIiwiaWF0IjoxNjMwODkwNDQ5fQ.VX4TGLsPCPtn2YfcJ_vRMz8nIK5z_QeQZDReRuf4wAk

{
    "title": "title43446",
    "url": "titledfsdfsdfdfgdfgdf1.com",
    "likes": 11110
}

###
GET http://localhost:3001/api/users/

###

GET http://localhost:3001/api/blogs